/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHeart: typeof import('~icons/mdi/heart')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
